dnaSequence = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"

length = len(dnaSequence)

exon1 = dnaSequence[0:63]
exon2 = dnaSequence[91:length]

print(exon1)
print(exon2)